#!/usr/bin/env bash
# Generates .env with fresh secrets for the local network. Refuses to overwrite
# an existing .env: the PDS's PLC rotation key must stay paired with the data
# in the volumes (see reset.sh).
set -euo pipefail
cd "$(dirname "$0")"

if [[ -f .env ]]; then
  echo ".env already exists; run ./reset.sh to start over" >&2
  exit 1
fi

hex() { openssl rand -hex "$1"; }

# secp256k1 private key as 32 bytes of hex, as in the official PDS installer.
rotation_key=$(openssl ecparam -name secp256k1 -genkey -noout -outform DER \
  | tail -c +8 | head -c 32 | xxd -p -c 32)

umask 077
cat > .env <<EOF
# Generated by init.sh. Local development only; never reuse these values.
POSTGRES_PASSWORD=$(hex 16)
PDS_JWT_SECRET=$(hex 16)
PDS_DPOP_SECRET=$(hex 32)
PDS_ADMIN_PASSWORD=$(hex 16)
PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX=$rotation_key
EOF
echo "wrote .env"
